### ISSUE TITLE
Establish compatibility with mods that introduce friendly entities of type "unit"

### ISSUE THREAD

**Issue by Derpumu** [Derpumu/Pacifist#61]
After #57 is merged, friendly units might get remove along with enemy units like biters.

Mods that come to mind: Mining Drones and all its forks, also Transport Drones, possibly other similar mods. I would guess that Pyanodon's has a few units as well.

Others that I found with a quick search: 
[ERM - Terran Units for Players](https://mods.factorio.com/mod/erm_terran)
[ERM - Zerg Units / Jormungand Brood](https://mods.factorio.com/mod/erm_zerg_exp)
[ERM - Protoss Units / Velari Tribe](https://mods.factorio.com/mod/erm_toss_exp)
[Total Automization](https://mods.factorio.com/mod/Total_Automization) (plus forks)

**Comment by dperelman** [comment]
I was thinking how you might distinguish these and one idea I had was that instead of removing all units, remove all units spawned by a unit_spawner. (Well, slightly different: remove units spawned by a unit_spawner that was removed and not spawned by any unit_spawner that wasn't removed in case there's some reason there's non-military units associated with a unit_spawner that I'm unaware of.)

**Comment by Derpumu** [comment]
I agree we should have a heuristic which units to remove - and probably look into unit-spawners as well. With the change of removing units in general, the following mods in my testing set were broken:

- Toxic_biters (marked incompatible)
- Explosive_biters (marked incompatible)
- pyalienlife (introduced exceptions)
- pyalternativeenergy (introduced exceptions)

That the first two are incompatible is fine by me, after all they just introduce biters, but I'd rather Pacifist silently remove everything those and similar mods add instead of having to maintain an ever growing list of mods that are incompatible.

I'll revisit this once I have tested and merged #58
